### PR TITLE
Delete references to javascript module no longer utilized.

### PR DESCRIPTION
**Pull request by dmischel**
Ready to merge and re-test. Testing should be done after confirming there are no listbox.* files in bwf_site/static.

### CODE REVIEW

**Comment by dmischel** [comment]
With the push of e6ac9ff this branch is ready to be merged and tested.

**Comment by billmania** [comment]
This version has an issue with the Admin function. No matter which Volunteer is select, I'm always shown my own profile.

**Comment by dmischel** [comment]
The selected Volunteer on the Admin page is now displayed.

**Comment by dmischel** [comment]
I have pushed a fix to mobile fonts to this branch because it will be next to merge with master and the fix needs to go in asap.

**Comment by dmischel** [comment]
The previous "fix" failed because it forced all templates to be mobile. This fix seems to work for both flavours and fixes mobile font selections.

**Pull request merged**
